/*
CONCEITOS:
FÁCIL:

WHERE, LIKE, ORDER BY, ASC/DESC, DESCRIBE

MÉDIO:

1 JOIN, FUNÇÕES MATEMÁTICAS (COUNT, AVG, MIN, MAX), CONCAT(), IFNULL()

DIFÍCIL:

+DE 1 JOIN, GROUP BY, LEFT/RIGHT JOIN, SUBQUERY, CASE WHEN

*/